<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Loja de carros</title>
        <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
        <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
        <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
        <link rel="stylesheet" href="/css/style.css">
        <style>
            body {
                margin: 50px 0 0 0;
                padding: 0;
                width: 100%;
                font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
                text-align: center;
                color: #aaa;
                font-size: 18px;
            }

            h2 {
                color: #aaa;
                letter-spacing: -3px;
                font-family: 'Lato', sans-serif;
                font-size: 70px;
                font-weight: 200;
                margin-bottom: 0;
            }
            #modelo {
                width: 50%;
            }


        </style>
    </head>
    <body>
    <form method="post" action="/config/" >
            <h2>LOJA DE CARROS</h2>
            <input name="modelo1" class="form-control" type="text" placeholder="modelo">
            <input name="marca1" class="form-control" type="text" placeholder="marca">
            <input name="ano1" class="form-control" type="text" placeholder="ano">
            
            <button type="button" class="btn btn-primary">enviar</button>
      
      </form>
    </body>
</html>
