<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>LOJÃO DE CARROS</title>
        <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
        <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
        <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
        <link rel="stylesheet" href="/css/style.css">
        <script src="/jquery/script.js"></script>
         
        <style>
           body {
                margin: 50px 0 0 0;
                padding: 0;
                width: 100%;
                font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
                text-align: center;
                color: #aaa;
                font-size: 18px;
            }

            h2 {
                color: #aaa;
                letter-spacing: -3px;
                font-family: 'Lato', sans-serif;
                font-size: 70px;
                font-weight: 200;
                margin-bottom: 0;
            }


        
        </style>
    </head>
    <body>
    <form method="post" action="/descricao/">
            <h2>LOJÃO DE CARROS</h2>
            <div class="form-group">
            <input name="modelo1" class="form-control" type="text" placeholder="digite o modelo">
            <input name="marca1" class="form-control" type="text" placeholder="digite a marca">
            <input name="ano1" class="form-control" type="text" placeholder="digite o ano">
            
            <a href="/categorias/"><button class="btn btn-primary">enviar</button></a>
            </div>
      </form>
            


    </body>

</html>
